### ISSUE TITLE
Oracle dialect raising error because method not implemented

### ISSUE THREAD

**Issue by davicente** [liangwenzhong/spider-sequelize-oracle#8]
Method objectToValues  is not implemented in file SqlString, and makes it fails

SqlString.objectToValues is not a function 
 TypeError: SqlString.objectToValues is not a function
    at Object.SqlString.escape (/app/node_modules/spider-sequelize-oracle/lib/dialects/oracle/sql-string.js:77:24)
    at Object.escape (/app/node_modules/spider-sequelize-oracle/lib/dialects/oracle/query-generator.js:1290:26)
    at Object.whereItemQuery (/app/node_modules/spider-sequelize-oracle/lib/dialects/abstract/query-generator.js:2063:20)
    at /app/node_modules/spider-sequelize-oracle/lib/dialects/abstract/query-generator.js:1730:25
    at /app/node_modules/spider-sequelize-oracle/node_modules/lodash/index.js:3073:15
    at baseForOwn (/app/node_modules/spider-sequelize-oracle/node_modules/lodash/index.js:2046:14)
    at Function.forOwn (/app/node_modules/spider-sequelize-oracle/node_modules/lodash/index.js:3378:16)
    at Object.whereItemsQuery (/app/node_modules/spider-sequelize-oracle/lib/dialects/abstract/query-generator.js:1729:9)
    at Object.getWhereConditions (/app/node_modules/spider-sequelize-oracle/lib/dialects/abstract/query-generator.js:2117:19)
    at Object.selectQuery (/app/node_modules/spider-sequelize-oracle/lib/dialects/oracle/query-generator.js:961:30)
    at QueryInterface.select (/app/node_modules/spider-sequelize-oracle/lib/query-interface.js:678:25)
    at Promise.try.then.then.then (/app/node_modules/sequelize/lib/model.js:1755:34)

**Comment by konarkjha** [comment]
> Method objectToValues is not implemented in file SqlString, and makes it fails
> 
> SqlString.objectToValues is not a function
> TypeError: SqlString.objectToValues is not a function
> at Object.SqlString.escape (/app/node_modules/spider-sequelize-oracle/lib/dialects/oracle/sql-string.js:77:24)
> at Object.escape (/app/node_modules/spider-sequelize-oracle/lib/dialects/oracle/query-generator.js:1290:26)
> at Object.whereItemQuery (/app/node_modules/spider-sequelize-oracle/lib/dialects/abstract/query-generator.js:2063:20)
> at /app/node_modules/spider-sequelize-oracle/lib/dialects/abstract/query-generator.js:1730:25
> at /app/node_modules/spider-sequelize-oracle/node_modules/lodash/index.js:3073:15
> at baseForOwn (/app/node_modules/spider-sequelize-oracle/node_modules/lodash/index.js:2046:14)
> at Function.forOwn (/app/node_modules/spider-sequelize-oracle/node_modules/lodash/index.js:3378:16)
> at Object.whereItemsQuery (/app/node_modules/spider-sequelize-oracle/lib/dialects/abstract/query-generator.js:1729:9)
> at Object.getWhereConditions (/app/node_modules/spider-sequelize-oracle/lib/dialects/abstract/query-generator.js:2117:19)
> at Object.selectQuery (/app/node_modules/spider-sequelize-oracle/lib/dialects/oracle/query-generator.js:961:30)
> at QueryInterface.select (/app/node_modules/spider-sequelize-oracle/lib/query-interface.js:678:25)
> at Promise.try.then.then.then (/app/node_modules/sequelize/lib/model.js:1755:34)

I am also facing the same issue, did you got any solution?
